import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import precision_score, recall_score, f1_score
from xgboost import XGBClassifier
from sklearn.metrics import average_precision_score
import joblib
import time

start_time = time.time()

# Read Data
df = pd.read_csv(r"..\data\SAML-D.csv")
dfc = df.copy()

# Feature Engineering
dfc["Datetime"] = pd.to_datetime(dfc["Date"] + ' ' + dfc["Time"], format="%Y-%m-%d %H:%M:%S")

# Sort by account and time to align physical row order with groupby output
dfc = dfc.sort_values(["Sender_account", "Datetime"])
dfc = dfc.set_index("Datetime")

# Calculate rolling stats and extract raw numpy values to bypass index alignment
dfc["sender_24h_sum"] = dfc.groupby("Sender_account")["Amount"].rolling("24h").sum().values
dfc["sender_24h_count"] = dfc.groupby("Sender_account")["Amount"].rolling("24h").count().values

# Fill potential NaNs generated by rolling calculations on empty prior windows
dfc["sender_24h_sum"] = dfc["sender_24h_sum"].fillna(0)
dfc["sender_24h_count"] = dfc["sender_24h_count"].fillna(0)

# Restore pure chronological sorting for the time-based train-test split
dfc = dfc.reset_index().sort_values("Datetime").reset_index(drop=True)

# Engineer time based columns
dfc["weekday"] = dfc["Datetime"].dt.day_name()
dfc["month"] = dfc["Datetime"].dt.month_name()
dfc["hour"] = dfc["Datetime"].dt.hour

# Engineer location/currency based columns
dfc["sender_receiver_location"] = dfc["Sender_bank_location"] + "-" + dfc["Receiver_bank_location"]
dfc["sender_receiver_currency"] = dfc["Payment_currency"] + "-" + dfc["Received_currency"]

# Engineer transaction type column
dfc["transaction_type"] = dfc["Laundering_type"].str.removeprefix("Normal_")

# Select X and y
y = dfc["Is_laundering"]
X = dfc[["Amount", "Payment_type", "weekday", "month", "hour", "sender_receiver_location", "sender_receiver_currency", "sender_24h_sum", "sender_24h_count", "transaction_type"]]

# Encode categorical X columns
cat_cols = ["Payment_type", "weekday", "month", "hour", "transaction_type"]
num_cols = ["Amount", "sender_24h_sum", "sender_24h_count", "curr_pair_freq", "loc_pair_freq"]

ct = ColumnTransformer(
    transformers=[
        (
            "onehot",
            OneHotEncoder(handle_unknown="ignore", sparse_output=True),
            cat_cols
        ),
        (
            "scaler",
            StandardScaler(),
            num_cols
        )
    ],
    remainder="drop"
)

# Approach 1: Class Weights
print("Approach 1: Class Weights")

# Train-Test Split
X_train_raw, X_test_raw, y_train, y_test = train_test_split(X, y, test_size=0.1, shuffle=False)
X_train_raw, X_val_raw, y_train, y_val = train_test_split(X_train_raw, y_train, test_size=0.1, shuffle=False)
assert y_val.sum() >= 50, "Validation set lacks positive cases. Script killed. Increase test_size."

X_train_raw = X_train_raw.copy()
X_val_raw = X_val_raw.copy()
X_test_raw = X_test_raw.copy()

# 1. Frequency Encoding for Currency Corridor
curr_freq = X_train_raw["sender_receiver_currency"].value_counts(normalize=True)
X_train_raw["curr_pair_freq"] = X_train_raw["sender_receiver_currency"].map(curr_freq)
X_val_raw["curr_pair_freq"] = X_val_raw["sender_receiver_currency"].map(curr_freq).fillna(0)
X_test_raw["curr_pair_freq"] = X_test_raw["sender_receiver_currency"].map(curr_freq).fillna(0)

# 2. Frequency Encoding for Location Corridor
loc_freq = X_train_raw["sender_receiver_location"].value_counts(normalize=True)
X_train_raw["loc_pair_freq"] = X_train_raw["sender_receiver_location"].map(loc_freq)
X_val_raw["loc_pair_freq"] = X_val_raw["sender_receiver_location"].map(loc_freq).fillna(0)
X_test_raw["loc_pair_freq"] = X_test_raw["sender_receiver_location"].map(loc_freq).fillna(0)

# 3. Drop the raw string columns
cols_to_drop = ["sender_receiver_currency", "sender_receiver_location"]
X_train_raw = X_train_raw.drop(columns=cols_to_drop)
X_val_raw = X_val_raw.drop(columns=cols_to_drop)
X_test_raw = X_test_raw.drop(columns=cols_to_drop)

X_train = ct.fit_transform(X_train_raw)
X_val = ct.transform(X_val_raw)
X_test = ct.transform(X_test_raw)

# Check distribution of y in train set and test set
print("\nChecking y distribution:")

print("\nOverall y:")
print(y.value_counts(normalize=True))

print("\nTrain Set:")
print(y_train.value_counts(normalize=True))

print("\nTest Set:")
print(y_test.value_counts(normalize=True))

# Calculate scale_pos_weight for XGBoost
scale_pos = (y_train == 0).sum() / (y_train == 1).sum()

# XGBoost
xgb_model = XGBClassifier(
    max_depth=6,
    learning_rate=0.05,
    n_estimators=3000,
    scale_pos_weight=scale_pos,
    max_delta_step=1,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method="hist",
    eval_metric="aucpr",
    early_stopping_rounds=50,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(
    X_train, 
    y_train, 
    eval_set=[(X_val, y_val)], 
    verbose=50
)

threshold=0.98
xgb_probs = xgb_model.predict_proba(X_test)[:, 1]
xgb_pred = (xgb_probs >= threshold).astype(int)

print("\nXGBoost Accuracy:")
print(accuracy_score(y_test, xgb_pred))

print("\nXGBoost Confusion Matrix:")
print(confusion_matrix(y_test, xgb_pred, normalize="true"))

print("\nXGBoost Classification Report:")
print(classification_report(y_test, xgb_pred))

print("\nXGBoost PR-AUC:")
xgb_probs = xgb_model.predict_proba(X_test)[:, 1]
print(average_precision_score(y_test, xgb_probs))

model_package = {
    "model": xgb_model,
    "threshold": threshold
}

# Export the package
joblib.dump(model_package, r"..\models\xgb_model_package.pkl")

# Runtime evaluation
end_time = time.time()

total_seconds = end_time-start_time
total_minutes = round((total_seconds/60),2)

print(f"\n\nScript took {total_minutes} minutes to run.")